---
title: "Comparison of the Exponential Distribution with the Central Limit Theorem"
author: "Tell Bennett"
date: "Monday, May 18, 2015"
output: pdf_document
---

Synopsis
--------

2-3 sentences.


Loading Packages
-----------------------------------

```{r loadpackages, echo = TRUE, results="hide", message=FALSE}
library(ggplot2)
library(dplyr)
```



```{r exp}
x <- (rexp(40, 0.2))
hist(x, breaks=30)
mean(x)
var(x)
y <- as.data.frame(x)
p <- ggplot(y, aes(x = x)) + theme_bw()
p + geom_histogram(aes(y = ..density..), alpha=0.5) + geom_density(size = 0.5, alpha = 0.2) + geom_vline(xintercept = 5, size = 0.5) 
```

#### Simulation - Exponential

Poisson(4) have variance 4; means of random samples of n Poisson(4) have sd 2/n−−√

```{r moresim3}
nosim <- 1000
n <- 40
z <- matrix(rexp(nosim * n, 0.2), nrow = nosim)
zmeans <- apply(z, 1, mean)
mean(zmeans)
var(zmeans)
hist(zmeans)
zdf <- as.data.frame(z)
zmdf <- as.data.frame(zmeans)

p <- ggplot(, aes(x = x)) + theme_bw()
p + geom_histogram(aes(y = ..density..), alpha=0.5) + geom_density(size = 0.5, alpha = 0.2) + geom_vline(xintercept = 5, size = 0.5) 

p2 <- ggplot(zdf, aes(x = V1)) + theme_bw()
p2 + geom_histogram(aes(y = ..density..), alpha=0.5) + geom_density(size = 0.5, alpha = 0.2) + geom_vline(xintercept = 5, size = 0.5) 

        + geom_density(size = 1, alpha = .2) 
        + geom_vline(xintercept = 5, size = 1) 
ggplot(zmdf, aes(x = zmeans)
        + geom_histogram()
        + geom_density(size = 1, alpha = .2) + geom_vline(xintercept = 5, size = 1)
```



#### This is the figure that asymptotically goes to the mean of 0
```{r lln1}
n <- 10000
means <- cumsum(rnorm(n)) / (1 : n) ### makes the cumulative average of n random normals

g <- ggplot(data.frame(x = 1 : n, y = means), aes(x = x, y = y)) 
g <- g + geom_hline(yintercept = 0) + geom_line(size = 2) 
g <- g + labs(x = "Number of obs", y = "Cumulative mean")
g
```


#### This is the figure comparing 10, 20, and 30 random normals - CLT, getting narrower
```{r moresim}
nosim <- 10000; 
dat <- data.frame(
    x = c(apply(matrix(rnorm(nosim * 10), nosim), 1, var),
          apply(matrix(rnorm(nosim * 20), nosim), 1, var),
          apply(matrix(rnorm(nosim * 30), nosim), 1, var)),
    n = factor(rep(c("10", "20", "30"), c(nosim, nosim, nosim))) 
    )
ggplot(dat, aes(x = x, fill = n)) + geom_density(size = 2, alpha = .2) + geom_vline(xintercept = 1, size = 2) 
```


#### Side by side figure of 10, 20, 30
```{r moresim2}
dat <- data.frame(
  x = c(apply(matrix(sample(1 : 6, nosim * 10, replace = TRUE), 
                     nosim), 1, var),
        apply(matrix(sample(1 : 6, nosim * 20, replace = TRUE), 
                     nosim), 1, var),
        apply(matrix(sample(1 : 6, nosim * 30, replace = TRUE), 
                     nosim), 1, var)
        ),
  size = factor(rep(c(10, 20, 30), rep(nosim, 3))))
g <- ggplot(dat, aes(x = x, fill = size)) + geom_histogram(alpha = .20, binwidth=.3, colour = "black") 
g <- g + geom_vline(xintercept = 2.92, size = 2)
g + facet_grid(. ~ size)
```


