---
output: html_document
---
## Notes from B Caffo week 2 lectures

### Intro to Variability

### Population variance

If $X$ is a random variable with mean $\mu$, the variance of $X$ is defined as

$$ Var(X) = E[(X - \mu)^2] = E[X^2] - E[X]^2 $$ 

The square root of the variance is called the standard deviation
The standard deviation has the same units as $X$


Ex. 1.  What's the variance from the result of a toss of a die?

$E[X] = 3.5$
    
$E[X^2] = 1 ^ 2 \times \frac{1}{6} + 2 ^ 2 \times \frac{1}{6} + 3 ^ 2 \times \frac{1}{6} + 4 ^ 2 \times \frac{1}{6} + 5 ^ 2 \times \frac{1}{6} + 6 ^ 2 \times \frac{1}{6} = 15.17$

$$Var(X) = E[X^2] - E[X]^2 \approx 2.92$$


Ex. 2.  What's the variance from the result of a biased coin flip - probability of heads (1) of $p$?

$E[X] = 0 \times (1 - p) + 1 \times p = p$

$E[X^2] = E[X] = p$

$$Var(X) = E[X^2] - E[X]^2 = p - p^2 = p(1 - p)$$  ### binomial distribution


```{r varfigure}
library(ggplot2)
xvals <- seq(-10, 10, by = .01)
dat <- data.frame(
    y = c(
        dnorm(xvals, mean = 0, sd = 1),
        dnorm(xvals, mean = 0, sd = 2),
        dnorm(xvals, mean = 0, sd = 3),
        dnorm(xvals, mean = 0, sd = 4)
    ),
    x = rep(xvals, 4),
    factor = factor(rep(1 : 4, rep(length(xvals), 4)))
)
ggplot(dat, aes(x = x, y = y, color = factor)) + geom_line(size = 2) 
```


### Sample Variance

The sample variance is $$ S^2 = \frac{\sum_{i=1} (X_i - \bar X)^2}{n-1} $$ (almost, but not quite, the average squared deviation from the sample mean)

* It is also a random variable
* It has an associate population distribution
* Its expected value is the population variance
* Its distribution gets more concentrated around the population variance with more data
* Its square root is the sample standard deviation
